# Generated by Django 3.0.8 on 2020-08-01 19:04

from django.db import migrations, models
import lessons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('title_video', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('title_description', models.TextField(blank=True, null=True)),
                ('term1', models.CharField(blank=True, max_length=255, null=True)),
                ('term1_description', models.TextField(blank=True, null=True)),
                ('term1_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('term2', models.CharField(blank=True, max_length=255, null=True)),
                ('term2_description', models.TextField(blank=True, null=True)),
                ('term2_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('term3', models.CharField(blank=True, max_length=255, null=True)),
                ('term3_description', models.TextField(blank=True, null=True)),
                ('term3_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('number_of_steps', models.IntegerField(blank=True, null=True)),
                ('step1_description', models.CharField(blank=True, max_length=255, null=True)),
                ('step1_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('step2_description', models.CharField(blank=True, max_length=255, null=True)),
                ('step2_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('step3_description', models.CharField(blank=True, max_length=255, null=True)),
                ('step3_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('step4_description', models.CharField(blank=True, max_length=255, null=True)),
                ('step4_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('step5_description', models.CharField(blank=True, max_length=255, null=True)),
                ('step5_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('step6_description', models.CharField(blank=True, max_length=255, null=True)),
                ('step6_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('step7_description', models.CharField(blank=True, max_length=255, null=True)),
                ('step7_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('step8_description', models.CharField(blank=True, max_length=255, null=True)),
                ('step8_image', models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_directory)),
                ('questions', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
