# Generated by Django 3.0.8 on 2020-08-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20200802_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='global_lesson_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
