# Generated by Django 3.0.8 on 2020-08-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20200802_0617'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='uniquelesson',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='user',
            field=models.CharField(default='sram', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('class_id', 'lesson_id', 'user'), name='unique-lesson'),
        ),
    ]
