# Generated by Django 3.0.8 on 2020-08-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20200803_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title_image',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
