# Generated by Django 3.0.8 on 2020-08-25 13:24

from django.db import migrations, models
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20200806_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='step1_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_step1_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='step2_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_step2_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='step3_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_step3_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='step4_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_step4_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='step5_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_step5_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='step6_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_step6_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='step7_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_step7_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='step8_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_step8_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='term1_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_term1_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='term2_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_term2_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='term3_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_term3_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_image',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_title_image),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_video',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.user_lesson_title_image),
        ),
    ]
